### ISSUE TITLE
Help with setup

### ISSUE THREAD

**Issue by obiknoven** [IBMStreams/streamsx.sparkMLLib#12]
Hi,

I have the following problem: I've added the streamsx.sparkmllib Toolkit in InfoSphere Streams Studio. Using the SparkCollaborativeFilteringALS operator, I get the following exception:

Exception in thread "Thread-11" java.lang.NoClassDefFoundError: org.apache.spark.SparkConf at com.ibm.streamsx.sparkmllib.AbstractSparkMLlibOperator.initialize(AbstractSparkMLlibOperator.java:132) at com.ibm.streams.operator.internal.runtime.api.OperatorAdapter.initialize(OperatorAdapter.java:713) at com.ibm.streams.operator.internal.jni.JNIBridge.(JNIBridge.java:275) Caused by: java.lang.ClassNotFoundException: org.apache.spark.SparkConf at java.net.URLClassLoader.findClass(URLClassLoader.java:607) at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:797) at java.lang.ClassLoader.loadClass(ClassLoader.java:775) at java.lang.ClassLoader.loadClass(ClassLoader.java:752) ... 3 more

CDISR5033E: An exception occurred during the execution of the SparkCollaborativeFilteringALS_3 operator. Processing element number 22 is terminating. CDISR4000E The processing element ID 22 of the application::MyProjectSpark_7 job with job ID 7 was submitted by the spark user, and then was shut down unexpectedly. The error is: Distillery Exception: 'virtual void SPL::PEImpl::process()' [./src/SPL/Runtime/ProcessingElement/PEImpl.cpp:873] with msg: Runtime failures occurred in the following operators: SparkCollaborativeFilteringALS_3..

Am I missing something during the setup?

Thank you in advance.

**Comment by ankitpas** [comment]
This seems like a classpath problem. Please make sure that SPARK_HOME is set to point to your spark installation at runtime.

**Comment by ankitpas** [comment]
I am assuming that after fixing the classpath, this is no longer an issue. Please reopen if its still a problem
